on:
  workflow_dispatch:
  push:
  create:
  release:
    types: [created]

name: Handle Release
jobs:
  # check-cosmo:
  #   if: "${{ ( github.event_name != 'push' ) || startsWith(github.event.head_commit.message, '[[ci]]') }}"
  #   runs-on: ubuntu-latest
  #   outputs:
  #     should-build-cosmo: ${{ steps.should-build.outputs.should-build-cosmo }}
  #   steps:
  #     - name: checkout the repository
  #       uses: actions/checkout@master
  #     - name: check if should build cosmo
  #       id: should-build
  #       env:
  #         GH_TOKEN: ${{ github.token }}
  #       run: |
  #         echo "should-build-cosmo=$(bash ./builder.sh should-build-cosmo)" >> "$GITHUB_OUTPUT"
  build-cosmo:
    if: "${{ ( github.event_name != 'push' ) || startsWith(github.event.head_commit.message, '[[ci]]') }}"

    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: checkout the repository
        uses: actions/checkout@master

      - name: get tag
        id: get-tag
        run: |
          echo "TAG=$(bash ./builder.sh get-tag)" >> "$GITHUB_OUTPUT"

      - name: check if should build cosmo
        id: should-build
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          echo "should-build-cosmo=$(bash ./builder.sh should-build-cosmo)" >> "$GITHUB_OUTPUT"

      - uses: actions/cache/restore@v4
        id: cache
        if: ${{ steps.should-build.outputs.should-build-cosmo == 'true' }}
        with:
          path: |
            ./.cosmocc
            ./o
          key: artifacts-cosmocc_${{ steps.get-tag.outputs.TAG }}
          restore-keys: |
            artifacts-cosmocc_

      - name: prepare cosmo repo
        if: ${{ steps.should-build.outputs.should-build-cosmo == 'true' }}
        run: bash ./builder.sh prepare-cosmo

      - name: restore timestamps
        if: ${{ steps.should-build.outputs.should-build-cosmo == 'true' }}
        uses: hsfzxjy/git-restore-mtime-action@master
        with:
          working-directory: "o/cosmopolitan"

      - name: restore build artifacts mtime
        if: ${{ steps.should-build.outputs.should-build-cosmo == 'true' && steps.cache.outputs.cache-hit == 'true' }}
        working-directory: o/cosmopolitan
        run: |
          LAST_HEAD=HEAD
          if [ -f o/.HEAD ]; then
            LAST_HEAD=$(cat o/.HEAD)
          fi
          echo HEAD: $(git rev-parse HEAD)
          echo LAST_HEAD: "$LAST_HEAD"
          if git merge-base --is-ancestor "$LAST_HEAD" HEAD; then
            while read mtime file; do
              [ -f "$file" ] && touch -d "@$mtime" "$file"
            done < o/.mtimes
          else
            rm o/
          fi

      - name: build cosmo
        if: ${{ steps.should-build.outputs.should-build-cosmo == 'true' }}
        env:
          GH_TOKEN: ${{ github.token }}
        run: bash ./builder.sh build-cosmo

      - name: pack cosmo
        id: pack-cosmo
        if: ${{ steps.should-build.outputs.should-build-cosmo == 'true' }}
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          files=$(bash ./builder.sh pack-cosmo)
          {
            echo "files<<EOF"
            echo "$files"
            echo "EOF"
          } >> "$GITHUB_OUTPUT"

      - name: save mtimes
        if: ${{ steps.should-build.outputs.should-build-cosmo == 'true' }}
        working-directory: o/cosmopolitan
        run: |
          find o -type f -exec stat -c "%Y %n" {} \; > o/.mtimes
          git rev-parse HEAD > o/.HEAD

      - uses: actions/cache/save@v4
        if: ${{ steps.should-build.outputs.should-build-cosmo == 'true' }}
        with:
          path: |
            ./.cosmocc
            ./o
          key: ${{ steps.cache.outputs.cache-primary-key }}

      - name: upload binaries to release
        if: ${{ steps.should-build.outputs.should-build-cosmo == 'true' }}
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "${{ steps.get-tag.outputs.TAG }}"
          files: ${{ steps.pack-cosmo.outputs.files }}
          fail_on_unmatched_files: true
          prerelease: true
  # cosmo-success:
  #   needs: build-cosmo
  #   runs-on: ubuntu-latest
  #   if: ${{ always() }}
  #   steps:
  #     - name: parse build-cosmo state
  #       # both success and skipped should be regarded as valid
  #       run: |
  #         if [ "${{ needs.build-cosmo.result }}" != "success" ] && [ "${{ needs.build-cosmo.result }}" != "skipped" ]; then
  #           echo "build-cosmo failed, exiting"
  #           exit 1
  #         fi
  define-gcc-targets:
    needs: build-cosmo
    runs-on: ubuntu-latest
    outputs:
      targets: ${{ steps.get-targets.outputs.targets }}
    steps:
      - name: checkout the repository
        uses: actions/checkout@master
      - name: get gcc targets
        id: get-targets
        run: |
          echo "targets=$(bash ./builder.sh gcc-targets)" >> "$GITHUB_OUTPUT"
  build-gcc:
    needs: define-gcc-targets
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        target: ${{fromJSON(needs.define-gcc-targets.outputs.targets)}}
    steps:
      - name: checkout the repository
        uses: actions/checkout@master

      - name: get tag
        id: get-tag
        run: |
          echo "TAG=$(bash ./builder.sh get-tag)" >> "$GITHUB_OUTPUT"

      - name: check should build gcc
        id: should-build-gcc
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          echo "should-build-gcc=$(bash ./builder.sh should-build-gcc ${{ matrix.target }})" >> "$GITHUB_OUTPUT"

      - name: build gcc
        if: ${{ steps.should-build-gcc.outputs.should-build-gcc == 'true' }}
        env:
          GH_TOKEN: ${{ github.token }}
        run: bash ./builder.sh build-gcc ${{ matrix.target }}

      - name: pack gcc
        if: ${{ steps.should-build-gcc.outputs.should-build-gcc == 'true' }}
        id: pack-gcc
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          files=$(bash ./builder.sh pack-gcc ${{ matrix.target }})
          {
            echo "files<<EOF"
            echo "$files"
            echo "EOF"
          } >> "$GITHUB_OUTPUT"

      - name: upload binaries to release
        if: ${{ steps.should-build-gcc.outputs.should-build-gcc == 'true' }}
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "${{ steps.get-tag.outputs.TAG }}"
          files: ${{ steps.pack-gcc.outputs.files }}
          fail_on_unmatched_files: true
